
device: cuda:0
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/home/bld/anaconda3/envs/raylib/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/bld/anaconda3/envs/raylib/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bld/HK_RL/RLagents_v3/scripts_0.py", line 99, in train_a2c
    action = np.random.choice(env.action_space.n, p=np.squeeze(probs[0].cpu().detach().numpy()))
  File "mtrand.pyx", line 956, in numpy.random.mtrand.RandomState.choice
